apiVersion: apps/v1
kind: Deployment                 
metadata:
  name: pythonapp
  labels:
    app: pythonapp             
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-deployment          
  template:                     
    metadata:
      labels:                    
        app: python-deployment 
    spec:
      containers:
      - name: python-deployment
        image: sebastesla1/python:1.0
        command: ["sh","-c","echo running on port 8000"]
        ports:
          - containerPort: 8000      
---
apiVersion: v1
kind: Service                    
metadata:
  name: attach
  labels:
    app: pythonapp   
spec:
  type: LoadBalancer                 
  ports:                         
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: python  
